apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
  labels:
    app: appointment-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-serivce
        image: 586794443713.dkr.ecr.ap-south-1.amazonaws.com/prod/helthsync/appointment-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hs-microservice
spec:
  selector:
    app: hs-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: LoadBalancer
