apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-serivce
        image: 586794443713.dkr.ecr.ap-south-1.amazonaws.com/prod/helthsync/notification-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-serivce
spec:
  selector:
    app: notification-serivce
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8084
  type: LoadBalancer
