apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-microservice
  namespace: testing
  labels:
    app: hs-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hs-microservice
  template:
    metadata:
      labels:
        app: hs-microservice
    spec:
      containers:
      - name: doctor-serivce
        image: chiranhw95/doctor-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
      - name: patient-serivce
        image: chiranhw95/patient-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
      - name: appointment-serivce
        image: chiranhw95/      - name: appointment-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: hs-microservice
  namespace: testing
spec:
  selector:
    app: hs-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
