apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service-deployment
  labels:
    app: doctor-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
      - name: doctor-serivce
        image: 586794443713.dkr.ecr.ap-south-1.amazonaws.com/test/helthsync/doctor-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-serivce
spec:
  selector:
    app: doctor-serivce
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: LoadBalancer
