apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deployment
  labels:
    app: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: doctor-serivce
        image: 586794443713.dkr.ecr.ap-south-1.amazonaws.com/test/helthsync/doctor-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
      - name: patient-serivce
        image: 586794443713.dkr.ecr.ap-south-1.amazonaws.com/test/helthsync/patient-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
      - name: appointment-serivce
        image: 586794443713.dkr.ecr.ap-south-1.amazonaws.com/test/helthsync/appointment-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: hs-microservice
  namespace: testing
spec:
  selector:
    app: hs-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
