version: '3.9'
services:
  patient-service:
    build:
      context: ./services/patient_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./services/patient_service/.env
    volumes:
      - ~/.aws:/root/.aws:ro
    image:
      chiranhw95/patient-service:latest

  appointment-service:
    build:
      context: ./services/appointment_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./services/appointment_service/.env
    volumes:
      - ~/.aws:/root/.aws:ro
    image:
      chiranhw95/appointment-service:latest

  # notification-service:
  #   build:
  #     context: ./services/notification_service
  #   ports:
  #     - "8002:8000"

  aggregator-service:
    build:
      context: ./services/aggregator_service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - ./services/aggregator_service/.env
    volumes:
      - ~/.aws:/root/.aws:ro
    image:
      chiranhw95/aggregator-service:latest

  doctor-service:
    build:
      context: ./services/doctor_service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    env_file:
      - ./services/doctor_service/.env
    volumes:
      - ~/.aws:/root/.aws:ro
    image:
      chiranhw95/doctor-service:latest
