version: '3.9'
services:
  patient-service:
    build:
      context: ./services/patient-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./services/patient-service/.env
    volumes:
      - ~/.aws:/root/.aws:ro
    image:
      chiranhw95/patient-service:latest

  appointment-service:
    build:
      context: ./services/appointment-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./services/appointment-service/.env
    volumes:
      - ~/.aws:/root/.aws:ro
    image:
      chiranhw95/appointment-service:latest

  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "8002:8000"

  aggregator-service:
    build:
      context: ./services/aggregator-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - ./services/aggregator-service/.env
    volumes:
      - ~/.aws:/root/.aws:ro
    image:
      chiranhw95/aggregator-service:latest

  doctor-service:
    build:
      context: ./services/doctor-service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    env_file:
      - ./services/doctor-service/.env
    volumes:
      - ~/.aws:/root/.aws:ro
    image:
      chiranhw95/doctor-service:latest
  
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: