pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
        TESTING_CLUSTER = 'helthsync-eks-test'
        PRODUCTION_CLUSTER = 'helthsync-eks-prod'
        DOCKER_REPO = 'chiranhw95'
        AWS_ACCOUNT_ID = '586794443713'
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_ACCESS_KEY_ID')
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }


        stage('Deploy Services to Testing ECR') {
            steps {
                withAWS(credentials: 'AWS_CREDS', region: "${AWS_DEFAULT_REGION}") {
                     script {
                        def services = ['patient-service', 'doctor-service','appointment-service', 'notification-service', 'aggregator-service']
                        def ecr_registry_id = """${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"""
                        for (service in services) {
                            sh """docker build --no-cache -t ${service}:latest ./services/${service}"""
                            sh """/usr/local/bin/aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ecr_registry_id}"""
                            sh """docker tag ${service}:latest ${ecr_registry_id}/test/helthsync/${service}:latest"""
                            sh """docker push ${ecr_registry_id}/test/helthsync/${service}"""
                        }
                     }
                }
                
            }
        }

        stage('Authenticate to AWS') {
            steps {
                withCredentials([aws(credentialsId: 'AWS_CREDS')]) {
                    sh 'aws sts get-caller-identity'
                }
            }
        }

        stage('Deploy services to Testing EKS') {
            steps {
                script {
                    def services = ['patient-service', 'doctor-service','appointment-service', 'notification-service', 'aggregator-service']
                    def ecr_registry_id = """${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"""
                    for (service in services) {
                        // Write the deployment.yaml dynamically
                        writeFile file: 'deployment.yaml', text: """
                        apiVersion: apps/v1
                        kind: Deployment
                        metadata:
                          name: ${service}-deployment
                          labels:
                            app: ${service}
                        spec:
                          replicas: 3
                          selector:
                            matchLabels:
                              app: ${service}
                        template:
                          metadata:
                            labels:
                              app: ${service}
                          spec:
                            containers:
                            - name: ${service}-container
                              image: ${ecr_registry_id}/test/helthsync/${service}:latest
                              ports:
                              - containerPort: 8080
                              resources:
                                requests:
                                  memory: "128Mi"
                                  cpu: "500m"
                                limits:
                                  memory: "256Mi"
                                  cpu: "1"
                        ---
                        apiVersion: v1
                        kind: Service
                        metadata:
                          name: ${service}
                        spec:
                          selector:
                            app: ${service}
                        ports:
                        - protocol: TCP
                          port: 80
                          targetPort: 8080
                        type: LoadBalancer
                        """

                        // Switch context to testing cluster
                        withCredentials([aws(credentialsId: 'AWS_CREDS')]) {
                            sh """
                            /usr/local/bin/aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${TESTING_CLUSTER}  --debug
                            kubectl apply -f deployment.yaml
                            """

                            // Verify deployment
                            sh """
                            kubectl get pods
                            kubectl get service ${service}
                            """
                        }
                    }
                }
            }
        }


        stage('Run Unit Tests') {
            steps {
                script {
                    // Run simple API tests
                    def testResult = sh(script: "curl -f https://299C0166393D40BE8FA1D8BBF89233F5.yl4.ap-south-1.eks.amazonaws.com/health", returnStatus: true)
                    if (testResult != 0) {
                        error "Tests failed on testing cluster"
                    }
                }
            }
        }

        stage('Deploy to Production Cluster') {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                script {
                    // Switch context to production cluster
                    sh """
                    aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${PRODUCTION_CLUSTER}
                    kubectl apply -f ./jenkins/k8s/production-deployment.yaml -n production
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs() // Clean workspace
        }
    }
}
