name: Deploy to Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Initialize Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Terraform Init and Apply
    - name: Terraform Init
      run: |
        cd infrastructure/terraform
        terraform init -backend-config="helthsync-terraform-state-bucket"
    - name: Terraform Plan
      run: terraform plan -out=tfplan -input=false
      working-directory: infrastructure/terraform
    - name: Terraform Apply
      run: terraform apply -input=false tfplan
      working-directory: infrastructure/terraform
